# API Guide

this doc to help record some func of np.


In [1]:
import numpy as np

## `np.nonzero`

- return the indices of the elem that are nonzero
- if the dimension > 1, it will return some sequences, in every sequence, it contains the indices in that dimension, and it is row-major and C-style 

In [2]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)

[[3 0 0]
 [0 4 0]
 [5 6 0]]


In [3]:
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

we can see, in the matrix, the (0,0),(1,1),(2,0),(2,1) are nonzero,we can use np.thranspose to make it more beautiful

In [4]:
np.transpose(np.nonzero(x))

array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]], dtype=int64)

`np.argwhere` have the same func, and it return a beautiful style directly

In [7]:
np.argwhere(x != 0)
# the condition are flexible, it can be x>3 etc.

array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]], dtype=int64)

- also np.nonzero(*a ndarray condition*) will achieve the same function of argwhere, also it return the indices

In [10]:
print(np.nonzero(x > 3))
print(np.argwhere(x > 3))
print(x > 3)
# we use the indices to find the value, the three type func equally

(array([1, 2, 2], dtype=int64), array([1, 0, 1], dtype=int64))
[[1 1]
 [2 0]
 [2 1]]
[[False False False]
 [False  True False]
 [ True  True False]]


In [11]:
print(x[np.nonzero(x > 3)])
print(x[np.argwhere(x > 3)]) # oh it is diff from the other two, because the array is not the C-style
print(x[x > 3])


[4 5 6]
[[[0 4 0]
  [0 4 0]]

 [[5 6 0]
  [3 0 0]]

 [[5 6 0]
  [0 4 0]]]
[4 5 6]


In [20]:
np.cov(x)

array([[ 3.        , -2.        ,  2.        ],
       [-2.        ,  5.33333333,  4.66666667],
       [ 2.        ,  4.66666667, 10.33333333]])